# Default values for lemp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nginx:
  tag: latest
  pullPolicy: IfNotPresent
  config: |
    server {
      listen 0.0.0.0:8080;
      server_name myapp.com;

      root /app/php-sample-app;

      location / {
        try_files $uri $uri/index.php;
      }

      location ~ \.php$ {
        # As php and nginx are in the same pod, we can access php-fpm service through localhost
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi.conf;
      }
    }
      
phpfpm:
  tag: latest
  pullPolicy: IfNotPresent

mariadb:
  tag: latest
  pullPolicy: IfNotPresent

imageInit:
  tag: stable
  pullPolicy: IfNotPresent  

postgresql:
  enabled: true
  postgresDatabase: ex03-db
  postgresPassword: ex03-pwd
  postgresUser: ex03-usu

  
service:
  type: ClusterIP
  port: 80
