kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "lemp.fullname" . }}-pvc
  labels:
    app: {{ template "lemp.name" . }}
    chart: {{ template "lemp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
