apiVersion: v1
kind: Secret
metadata:
metadata:
  name: {{ template "lemp.fullname" . }}-secrets
  labels:
    app: {{ template "lemp.name" . }}
    chart: {{ template "lemp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: cm9vdA==

