apiVersion: v1
kind: Service
metadata:
  name: {{ template "lemp.fullname" . }}mariadb
  labels:
    app: {{ template "lemp.name" . }}mariadb
    chart: {{ template "lemp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.serviceMariadb.type }}
  ports:
    - port: {{ .Values.serviceMariadb.port }}
      targetPort: 3306
      name: db-port
  selector:
    app: {{ template "lemp.name" . }}
    release: {{ .Release.Name }}mariadb
