apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lemp.fullname" . }}
  labels:
    app: {{ template "lemp.name" . }}
    chart: {{ template "lemp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  dbName: {{ .Values.secretsmariadb.dbname }}
  dbUser: {{ .Values.secretsmariadb.dbuser }}
  dbPass: {{ .Values.secretsmariadb.dbpass }}
