apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lemp.fullname" . }}-cm
  labels:
    app: {{ template "lemp.name" . }}
    chart: {{ template "lemp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
data:
  myapp.conf: |-
{{ .Values.nginx.config | indent 4 }}
