apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "lemp.fullname" . }}
  labels:
    app: {{ template "lemp.name" . }}
    chart: {{ template "lemp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "lemp.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "lemp.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ printf "%s-nginx-%s" .Chart.Name .Values.nginx.tag }}
          image: {{ printf "%s:%s" "bitnami/nginx"  .Values.nginx.tag }}
          imagePullPolicy: {{ .Values.nginx.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: {{ template "lemp.fullname" . }}-vm
              mountPath: /etc/config
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
        - name: {{ printf "%s-phpfpm-%s" .Chart.Name .Values.phpfpm.tag }}
          image: {{ printf "%s:%s" "bitnami/php-fpm"  .Values.phpfpm.tag }}
          imagePullPolicy: {{ .Values.phpfpm.pullPolicy }}
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP                            
      volumes:
        - name: {{ template "lemp.fullname" . }}-vm
          configMap:
            name: {{ template "lemp.fullname" . }}-cm
            
